@isTest
public class TestServiceQueryUtils {
    @isTest
    public static void getConfigurationsTest(){
        /*
        Configuration__c configuration = new Configuration__c();
        configuration.Name = 'new configuration';
        configuration.Object__c = 'Lead';
        configuration.Skill_Based_Routing__c = true;
        configuration.Model__c = 'MD 404';
        configuration.Skill_Based_Routing_Field__c = 'Name';
        configuration.Skill_Based_Routing_Value__c = 'Performance';
        configuration.Status_Close_Field__c = 'Title';
        configuration.Status_Close_Value__c = 'Aman';
        configuration.Agent_Capacity__c = 12;
		insert configuration;   
        
        Configuration_Skill_Fields__c configurationFields = new Configuration_Skill_Fields__c();
        //configurationFields.Name = 'Last Name';
       	configurationFields.Field_Name__c = 'FirstName';
        configurationFields.Configuration__c = configuration.Id;
        insert configurationFields;
        
        Configuration_Skill__c confSkill = new Configuration_Skill__c();
        confSkill.Skill_Name__c = 'Reason';
        confSkill.Configuration__c = configuration.Id;
        confSkill.Configuration_Skill_Field__c = configurationFields.Id;
        insert confSkill;
        
        List<String> onlineUserList = new  List<String>();
        onlineUserList.add(confSkill.Skill_Name__c);
        
        //ServiceQueryUtils.getConfigurations();
        
        //ServiceQueryUtils.getSkillBasedroution();
        
        //ServiceQueryUtils.serviceUserSkillList(onlineUserList);
        
        //ServiceQueryUtils.ConfigurationSkillFields(configuration.Id);
        
        //ServiceQueryUtils.getQueues();
        
        ServiceQueryUtils.getUserSkill();
        */
    }

}